name: Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  upload-release-assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Upload assets for release
        run: |
          gh release upload -R "$gh_repo" "$gh_tag" ghidra_*_GhidraNes.zip
        env:
          gh_repo: ${{ github.repository }}
          gh_tag: ${{ github.ref_name }}
